require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
